# Generated by Django 5.1.4 on 2026-03-05 18:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_file', models.ImageField(upload_to='medical_images/originals/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CroppedImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cropped_file', models.ImageField(upload_to='medical_images/crops/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='predictor.medicalimage')),
            ],
        ),
    ]
