# Generated by Django 5.1.4 on 2026-03-06 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0002_scan'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='heatmap_image',
            field=models.ImageField(blank=True, null=True, upload_to='analysis/heatmaps/'),
        ),
        migrations.AddField(
            model_name='scan',
            name='roi_image',
            field=models.ImageField(blank=True, null=True, upload_to='analysis/roi/'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='risk_level',
            field=models.CharField(choices=[('Low', 'Low Risk'), ('Moderate', 'Moderate Risk'), ('High', 'High Risk')], max_length=20),
        ),
    ]
